// Skill id -> display name. Mirrors showeq-daemon/src/skills.h.
const SKILL_NAMES: Record<number, string> = {
  0:  '1H Blunt',
  1:  '1H Slashing',
  2:  '2H Blunt',
  3:  '2H Slashing',
  4:  'Abjuration',
  5:  'Alteration',
  6:  'Apply Poison',
  7:  'Archery',
  8:  'Backstab',
  9:  'Bind Wound',
  10: 'Bash',
  11: 'Block',
  12: 'Brass Instruments',
  13: 'Channeling',
  14: 'Conjuration',
  15: 'Defense',
  16: 'Disarm',
  17: 'Disarm Traps',
  18: 'Divination',
  19: 'Dodge',
  20: 'Double Attack',
  21: 'Dragon Punch',
  22: 'Dual Wield',
  23: 'Eagle Strike',
  24: 'Evocation',
  25: 'Feign Death',
  26: 'Flying Kick',
  27: 'Forage',
  28: 'Hand to Hand',
  29: 'Hide',
  30: 'Kick',
  31: 'Meditate',
  32: 'Mend',
  33: 'Offense',
  34: 'Parry',
  35: 'Pick Lock',
  36: '1H Piercing',
  37: 'Riposte',
  38: 'Round Kick',
  39: 'Safe Fall',
  40: 'Sense Heading',
  41: 'Sing',
  42: 'Sneak',
  43: 'Specialize Abjure',
  44: 'Specialize Alteration',
  45: 'Specialize Conjuration',
  46: 'Specialize Divination',
  47: 'Specialize Evocation',
  48: 'Pick Pockets',
  49: 'Stringed Instruments',
  50: 'Swimming',
  51: 'Throwing',
  52: 'Tiger Claw',
  53: 'Tracking',
  54: 'Wind Instruments',
  55: 'Fishing',
  56: 'Make Poison',
  57: 'Tinkering',
  58: 'Research',
  59: 'Alchemy',
  60: 'Baking',
  61: 'Tailoring',
  62: 'Sense Traps',
  63: 'Blacksmithing',
  64: 'Fletching',
  65: 'Brewing',
  66: 'Alcohol Tolerance',
  67: 'Begging',
  68: 'Jewelry Making',
  69: 'Pottery',
  70: 'Percussion Instruments',
  71: 'Intimidation',
  72: 'Berserking',
  73: 'Taunt',
  74: 'Frenzy',
  75: 'Triple Attack', // standard modern-EQ addition after Frenzy
  76: '2H Piercing',   // standard modern-EQ addition
  // eql skill ids 77-82 are real skills (77/79/80/82 observed nonzero in a
  // profile dump, scaling with level; 75/78/81 read 0 for the sampled multiclass
  // char) but lack an authoritative enum->name mapping (eqstr_us.txt keys skill
  // names by string id, not skill index). They fall through to the `Skill N`
  // placeholder below until named.
};

export function skillNameOf(id: number): string {
  return SKILL_NAMES[id] ?? `Skill ${id}`;
}
